spring.datasource.url=jdbc:mysql://localhost:3306/chat?serverTimezone=UTC&useSSL=false
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.username=root
spring.datasource.password=1234

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

spring.redis.host=localhost
spring.redis.port=6379
firebase.config.path=src/main/resources/firebase/chat-63b7d-firebase-adminsdk-fbsvc-993a8a2ec9.json

server.port=8080

spring.jackson.serialization.fail-on-empty-beans=false

logging.level.org.springframework.security=DEBUG
